name: Shared Ptr CMake CI

on: [push, pull_request]

jobs:
  ctest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Create build folder
      working-directory: homework/shared_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/shared_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/shared_ptr/build
      run: ctest -V
  valgrind:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Download and install valgrind
      run: |
        sudo apt-get update && sudo apt-get install valgrind
    - name: Create build folder
      working-directory: homework/shared_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/shared_ptr/build
      run: |
        cmake ..
        make
    - name: Run valgrind
      working-directory: homework/shared_ptr/build
      run: |
        valgrind --leak-check=full ./sharedPtr-ut
